[package]
name = "fishnet"
version = "0.1.0"
edition = "2024"

[dependencies]
smol = "2.0.2"
async-channel = "2.5.0"
async-dup = "1.2.4"
clap = { version = "4.5.13", features = ["derive"] }
rand = "0.9.2"
owo-colors = "4.2.2"
regex = "1.11.3"
